### ISSUE TITLE
Add link to a graph of latest actions of an abusefilter

### ISSUE THREAD

**Issue by he7d3r** [MusikAnimal/MusikBot#14]
Do you think we could add a links somewhere at
https://pt.wikipedia.org/wiki/User:MusikBot/StaleFilters/Report
pointing to graphs like https://tools.wmflabs.org/ptwikis/Filters:ptwiki:109&126&140&146&26&31&77 ?
(maybe each row in the table could have a separate link, or we could use a single link for all of them as above)

**Comment by MusHOikAniEmal** [comment]
bitch pls y close

**Comment by MusHOikAniEmal** [comment]
@sagan @niko @jackmcbarn @samtar @logan @cyberpower678 @deskana @samwalton9 @ks0stm @slakr @cameron11598 @barras @FastLizard4 @krenair @snowolf @allthefoxes @earwig @ksft @datguy @jianhui67 @tbloemink @pokefan95 @justberry @marktraceur @revent @grumble @stwalkerster @notaspy @uyscuti @idoh @k6ka @e @fluffernutter @keegan @steinsplitter @l235 @alexz @oshwah

**Comment by MusHOikAniEmal** [comment]
yoyo :dagger:

**Comment by MusHOikAniEmal** [comment]
time for more dox??

**Comment by MusHOikAniEmal** [comment]
lmaooo

**Comment by MusikAnimal** [comment]
@he7d3r This is a very cool tool! I am inclined to add links to it for each row and at the top. Thanks for sharing! I see there are other really nice filter-related tools by this author, but it seems to only support ptwiki :(

**Comment by he7d3r** [comment]
The tool can be used with English Wikipedia like this:
https://tools.wmflabs.org/ptwikis/Filters:enwiki
https://tools.wmflabs.org/ptwikis/Filters:enwiki:135
[@danilomac](https://github.com/danilomac) maintains the source code at https://github.com/ptwikis/ptwikis

**Comment by MusikAnimal** [comment]
Thanks, https://tools.wmflabs.org/ptwikis/Filters:enwiki was the other tool I was looking for. Works wonderfully!

I've taken this request a step further and am setting it up so that you can define your own links, much in the same way as a MediaWiki message. To add links for each filter in the report, create the page [User:MusikBot/StaleFilters/Report/Links](https://pt.wikipedia.org/wiki/User:MusikBot/StaleFilters/Report/Links) and put a $1 where the filter ID goes. So for enwiki I'm using `[https://tools.wmflabs.org/ptwikis/Filters:enwiki:$1 Graph]`. This allows you to change the links if need be, say if the tool went down or there are other tools you want to link to as well, etc. See the report with the links column: https://en.wikipedia.org/wiki/User:MusikBot/StaleFilters/Report

If User:MusikBot/StaleFilters/Report/Links does not exist or is blank the "Links" column is not shown. The i18n message `links` for the column heading is [here](https://github.com/MusikAnimal/MusikBot/blob/master/dictionaries/pt/general.yml#L13), please translate accordingly. Google Translate seemed to think it was just that, "Links", and same for French.

Following this system there isn't a good way to add a configurable message above the report, since `$1` would have to be an array, that you would somehow have to iterate over. Hopefully the per-filter links will suffice for now :)

Let me know what you think!

**Comment by MusikAnimal** [comment]
@he7d3r To make sure you see this

**Comment by MusikAnimal** [comment]
Another thing, maybe you have some insight: I was trying to add links to this tool via actual MediaWiki interface messages at Special:AbuseFilter/:id but it seems all the messages are escaped. I tried [MediaWiki:Abusefilter-edit-status](https://en.wikipedia.org/wiki/MediaWiki:Abusefilter-edit-status) and [MediaWiki:Abusefilter-edit-subtitle](https://en.wikipedia.org/wiki/MediaWiki:Abusefilter-edit-subtitle). Both will show the syntax `[[link]]` or `[link]` rather than actually make it a link :( Any ideas?

**Comment by he7d3r** [comment]
Yeah, MediaWiki:Abusefilter-edit-status is escaped by the extension (see [AbuseFilterViewEdit.php#L405](https://github.com/wikimedia/mediawiki-extensions-AbuseFilter/blob/4b2fa7c6abbfab5414b12a211c428630cdfd40b0/Views/AbuseFilterViewEdit.php#L405)).

**Comment by MusikAnimal** [comment]
Hopefully that will change! See https://phabricator.wikimedia.org/T157235 and https://gerrit.wikimedia.org/r/#/c/336166/

**Comment by MusikAnimal** [comment]
The patch to remove escaping of `abusefilter-edit-subtitle-new` and `abusefilter-edit-status-label` has been deployed :) On enwiki we're linking to the tool in the status with https://en.wikipedia.org/w/index.php?title=MediaWiki:Abusefilter-edit-status&oldid=764627151 Going to assume it's safe to close than issue. Cheers
